# Generated by Django 6.0.6 on 2026-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                default="aLCV8OMIkN6Jhhx4g6uHXN4ZOHcHNmoc2SF2AI5uO6uYcyUnCWyWo5St8Zml3cXL7Fl4a2rs9i6CCJX4obp1bIx1TMYmiF0ZDOiiN4w5yxkQMNtVxM2i6wxz9WNaB1oy",
                max_length=128,
                verbose_name="کد فعالسازی حساب کاربری",
            ),
        ),
    ]
