# Generated by Django 6.0.6 on 2026-07-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_email_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                default="Jsd2i4icLfRxCGsr03jL4M4UeMgVr2WGMbbdMvBCRu3YqIOHhz5CXv3gr3TSeZkdZEMvR4o8TNgdYg7LBzCyI08XSVavkLbosjpfPzIIaNz48w7eSJ7vfLVoyTMVnjII",
                max_length=128,
                verbose_name="کد فعالسازی حساب کاربری",
            ),
        ),
    ]
