# Generated by Django 6.0.6 on 2026-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_email_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                max_length=128, verbose_name="کد فعالسازی حساب کاربری"
            ),
        ),
    ]
