# Generated by Django 6.0.6 on 2026-08-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='accounts',
        ),
    ]
