# Generated by Django 6.0.6 on 2026-07-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_email_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                default="zqAmYIvd3JzFuNVGxNaTANyhttIlGFl6rgILFqXuqvj25mDJBfk5KjoRsyjio4kuYKNzFuyWijXboJomTQ4n1YIRdkCaqgy0GhmcRUmsRDKMhyo2aFB23mMLvPdZWWOE",
                max_length=128,
                verbose_name="کد فعالسازی حساب کاربری",
            ),
        ),
    ]
