# Generated by Django 6.0.6 on 2026-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_email_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                default="PanrKPZ2Oc096HZBE1NraQuduwUJi94I7HkCeUCN3w7Q2tbcSMu4FUatI33uKg4aRV86FUm4nZ9GKmWDlv4HtIcwcnULtgXkMVAziYBsIWX00t6o2aRLQrbkOh3J16Zz",
                max_length=128,
                verbose_name="کد فعالسازی حساب کاربری",
            ),
        ),
    ]
