# Generated by Django 6.0.6 on 2026-07-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_email_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                default="Grog5eXWWxiQOEZZ44jk42WNmiJUNohqLTaCvk6mRZiU6FLKQ6JePHbMkibob8iVxSHPd3RelJbiPpGr2kr7cNs7uiL9eCHzIpid7OcFDLwGyQHbi8qT2rkEv5VOUV5u",
                max_length=128,
                verbose_name="کد فعالسازی حساب کاربری",
            ),
        ),
    ]
