# Generated by Django 6.0.6 on 2026-07-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="نام دسته بندی"),
                ),
                (
                    "url_name",
                    models.SlugField(
                        max_length=120, verbose_name="آدرس دسته بندی در url"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.category",
                        verbose_name="دسته بندی والد",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
                "db_table_comment": "This table for products` categories",
                "ordering": ["is_active", "name", "url_name"],
            },
        ),
    ]
