# Generated by Django 6.0.6 on 2026-07-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="فقط برای دسته بندی های والد استفاده می شود",
                null=True,
                upload_to="category/image",
                verbose_name="عکس دسته بندی",
            ),
        ),
    ]
