# Generated by Django 6.0.6 on 2026-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_category_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="نام برند"
                    ),
                ),
                (
                    "url_name",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="آدرس برند در url"
                    ),
                ),
            ],
            options={
                "db_table": "brands",
                "db_table_comment": "This table for products` brands",
                "ordering": ["is_active", "name", "url_name"],
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="نام دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="url_name",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="آدرس دسته بندی در url"
            ),
        ),
    ]
