# Generated by Django 6.0.6 on 2026-07-20 17:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_brand_alter_category_name_alter_category_url_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="رنگ / حافطه داخلی و ...",
                    ),
                ),
            ],
            options={
                "db_table": "attribute",
                "db_table_comment": "",
                "ordering": ["is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        max_length=155,
                        null=True,
                        verbose_name="مقدار ویژگی",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="اگر از ویژگی رنگ استفاده کردی کد رنگ رو اینجا بزار",
                        max_length=7,
                        null=True,
                        verbose_name="کد رنگ",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values_attr",
                        to="product.attribute",
                        verbose_name="ویژگی",
                    ),
                ),
            ],
            options={
                "db_table": "attribute_values",
                "db_table_comment": "",
                "ordering": ["is_active", "value"],
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام محصول")),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="توضیحات کوتاه محصول",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات اصلی محصول"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="آدرس محصول در url"),
                ),
                (
                    "count_view",
                    models.PositiveIntegerField(
                        default=0, verbose_name="بازدید از محصول"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="product.brand",
                        verbose_name="برند محصول",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="product.category",
                        verbose_name="دسته بندی محصول",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "db_table_comment": "This table is for defining products.",
                "ordering": ["is_active", "name", "category"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام ویژگی")),
                ("value", models.CharField(max_length=255, verbose_name="مقدار ویژگی")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_specifications",
                "db_table_comment": "This table is for product technical specifications and is related to the products table.",
                "ordering": ["is_active", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="قیمت محصول")),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="موجودی محصول"
                    ),
                ),
                (
                    "discount",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="اگر می خواهید برای این محصول تخفیف بزارید این فیلد باید پر شود",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد به فروش رفته"
                    ),
                ),
                (
                    "attributes",
                    models.ManyToManyField(
                        related_name="variants", to="product.attributevalue"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="product.product",
                        verbose_name="محصول والد",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant",
                "db_table_comment": "",
                "ordering": ["is_active", "stock"],
            },
        ),
        migrations.CreateModel(
            name="ProductsImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product/image", verbose_name="عکس محصول"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="عکس اصلی / غیر اصلی"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر این عکس مخصوص محصول خاصی است مثل رنگ قرمز",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "products_images",
                "db_table_comment": "",
                "ordering": ["is_active"],
            },
        ),
    ]
