# Generated by Django 6.0.6 on 2026-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_attribute_attributevalue_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspecification",
            name="is_key_feature",
            field=models.BooleanField(default=False, verbose_name="ویژگی کلیدی"),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="is_quick_info",
            field=models.BooleanField(default=False, verbose_name="اطلاعات سریع"),
        ),
    ]
