# Generated by Django 6.0.6 on 2026-07-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_productspecification_is_key_feature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspecification",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="اگر تیک ویژگی کلیدی را زده اید توضیح ویژگی را اینجا بگذارید",
                max_length=255,
                null=True,
                verbose_name="توضیحی در مورد ویژگی",
            ),
        ),
    ]
