# Generated by Django 6.0.6 on 2026-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_productspecification_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام تگ"
                    ),
                ),
            ],
            options={
                "db_table": "tags",
                "db_table_comment": "This is for tag`s products",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, to="product.tag", verbose_name="تگ های محصول"
            ),
        ),
    ]
