# Generated by Django 6.0.6 on 2026-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_tag_product_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tag",
        ),
        migrations.AddField(
            model_name="tag",
            name="Product",
            field=models.ManyToManyField(to="product.product", verbose_name="محصولات"),
        ),
    ]
