# Generated by Django 6.0.6 on 2026-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_remove_product_tag_tag_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="Product",
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, to="product.tag", verbose_name="تگ های محصول"
            ),
        ),
    ]
