# Generated by Django 6.0.6 on 2026-07-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_remove_tag_product_product_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=155, verbose_name="نام دسته بندی ویژگی"
                    ),
                ),
            ],
            options={
                "ordering": ["is_active"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="productspecification",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.specificationcategory",
                verbose_name="دسته بندی ویژگی",
            ),
        ),
    ]
