# Generated by Django 6.0.6 on 2026-07-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_specificationcategory_productspecification_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecification",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_specification",
                to="product.specificationcategory",
                verbose_name="دسته بندی ویژگی",
            ),
        ),
    ]
