# Generated by Django 6.0.6 on 2026-07-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_alter_productspecification_category"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="specificationcategory",
            table_comment="d",
        ),
        migrations.AlterModelTable(
            name="specificationcategory",
            table="specificationcategory",
        ),
    ]
