# Generated by Django 6.0.6 on 2026-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_specificationcategory_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specificationcategory",
            options={"ordering": ["is_active", "order"]},
        ),
        migrations.AddField(
            model_name="specificationcategory",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
    ]
