# Generated by Django 6.0.6 on 2026-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_alter_specificationcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("question", models.TextField(verbose_name="پرسش")),
                ("answer", models.TextField(verbose_name="پاسخ")),
            ],
            options={
                "db_table": "product_question_answers",
                "db_table_comment": "d",
                "ordering": ["is_active"],
            },
        ),
        migrations.AlterModelOptions(
            name="specificationcategory",
            options={"ordering": ["order"]},
        ),
    ]
