# Generated by Django 6.0.6 on 2026-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_productquestionanswer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDeliveryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("title", models.CharField(max_length=55, verbose_name="عنوان")),
                ("description", models.CharField(max_length=255)),
                (
                    "emojy",
                    models.CharField(
                        blank=True,
                        help_text="برای قشنگی بزاریش خیلی بهتر عمویی",
                        max_length=10,
                        verbose_name="اموجی",
                    ),
                ),
            ],
            options={
                "db_table": "product_delivery_info",
                "db_table_comment": "f",
                "ordering": ["is_active"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_info",
            field=models.ManyToManyField(
                related_name="delivery_info",
                to="product.productdeliveryinfo",
                verbose_name="برای کدام محصولات",
            ),
        ),
    ]
