# Generated by Django 6.0.6 on 2026-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_productdeliveryinfo_product_delivery_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productdeliveryinfo",
            old_name="emojy",
            new_name="emoji",
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_info",
            field=models.ManyToManyField(
                to="product.productdeliveryinfo",
                verbose_name="اطلاعاتی مانند نوع بسته بندی و این حرفا",
            ),
        ),
        migrations.AlterField(
            model_name="productdeliveryinfo",
            name="description",
            field=models.CharField(max_length=255, verbose_name="توضیحات"),
        ),
    ]
