# Generated by Django 6.0.6 on 2026-07-26 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_rename_emojy_productdeliveryinfo_emoji_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان کامنت",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="متن کامنت")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="ناشناس",
                        help_text="اگر کسی در سایت ما ثبت نام نکرده باشد و سپس کامنت بزاره ما اسمش رو از اینحا میزاریم اگر اسم پر نکنه به عنوان ناشناس این رو نشون میدیم",
                        max_length=100,
                        null=True,
                        verbose_name="نام نویسنده",
                    ),
                ),
                (
                    "like",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="لایک"
                    ),
                ),
                (
                    "diclike",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="دیسلایک"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر کاربری که در سایت ثبت نام کرده باشد و این کامنت را بگذارد این مقدار پر می شود",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "db_table": "comments_products",
                "db_table_comment": "c",
                "ordering": ["is_active", "-created_at"],
            },
        ),
    ]
