# Generated by Django 6.0.6 on 2026-07-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="product.product",
                verbose_name="محصول",
            ),
        ),
    ]
