# Generated by Django 6.0.6 on 2026-07-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_alter_comments_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="diclike",
            new_name="dislike",
        ),
    ]
