# Generated by Django 6.0.6 on 2026-07-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_rename_comments_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=255, verbose_name="متن کامنت"),
        ),
    ]
