# Generated by Django 6.0.6 on 2026-07-26 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_alter_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.SmallIntegerField(
                default=2,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="امتیاز",
            ),
            preserve_default=False,
        ),
    ]
