# Generated by Django 6.0.6 on 2026-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_comment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="emoji",
            field=models.CharField(
                default="🟦", max_length=10, verbose_name="ایموجی این دسته بندی"
            ),
        ),
    ]
