# Generated by Django 6.0.6 on 2026-08-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_category_emoji'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='attribute',
            table_comment='This table lists the product attributes based on which the user selects the specific product—with its particular specifications—to add to the shopping cart.',
        ),
        migrations.AlterModelTableComment(
            name='attributevalue',
            table_comment='This table holds the value for that product attribute; for example, if the attribute is color, both the color code and the color name are included.',
        ),
        migrations.AlterModelTableComment(
            name='brand',
            table_comment='The brand of the products is listed in this table.',
        ),
        migrations.AlterModelTableComment(
            name='category',
            table_comment='The product categories are listed in this table.',
        ),
        migrations.AlterModelTableComment(
            name='comment',
            table_comment='This table is for product comments.',
        ),
        migrations.AlterModelTableComment(
            name='product',
            table_comment='An overview of our products is provided in this table.',
        ),
        migrations.AlterModelTableComment(
            name='productquestionanswer',
            table_comment='This table is for product-related questions and answers.',
        ),
        migrations.AlterModelTableComment(
            name='productsimages',
            table_comment='This table is for product photos.',
        ),
        migrations.AlterModelTableComment(
            name='productspecification',
            table_comment='This table contains the product specifications.',
        ),
        migrations.AlterModelTableComment(
            name='productvariant',
            table_comment='This table shows the variations of a product that are maintained within that product.',
        ),
        migrations.AlterModelTableComment(
            name='specificationcategory',
            table_comment='This table is for attribute categories.',
        ),
        migrations.AlterModelTableComment(
            name='tag',
            table_comment='The tags for the products are listed in this table.',
        ),
        migrations.AlterModelTable(
            name='productsimages',
            table='product_images',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variants',
        ),
        migrations.AlterModelTable(
            name='specificationcategory',
            table='specification_categories',
        ),
    ]
