# Generated by Django 6.0.6 on 2026-08-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_attribute_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['is_active', '-order']},
        ),
        migrations.AlterModelOptions(
            name='specificationcategory',
            options={'ordering': ['-order']},
        ),
    ]
