# Generated by Django 6.0.6 on 2026-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_info',
            field=models.ManyToManyField(blank=True, null=True, to='product.productdeliveryinfo', verbose_name='اطلاعاتی مانند نوع بسته بندی و این حرفا'),
        ),
    ]
