# Generated by Django 6.0.6 on 2026-08-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_delivery_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductQuestionAnswer',
        ),
    ]
