# Generated by Django 6.0.6 on 2026-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_delete_productquestionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_info',
            field=models.ManyToManyField(to='product.productdeliveryinfo', verbose_name='اطلاعاتی مانند نوع بسته بندی و این حرفا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='product.tag', verbose_name='تگ های محصول'),
        ),
    ]
