# Generated by Django 6.0.6 on 2026-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_delivery_info_alter_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('short_title', models.CharField(max_length=35, verbose_name='عنوان کوتاه')),
                ('main_title', models.CharField(max_length=120, verbose_name='عنوان اصلی')),
                ('description', models.CharField(max_length=350, verbose_name='توضیحات')),
                ('btn_text', models.CharField(max_length=55, verbose_name='متن درون دکمه')),
                ('btn_url', models.CharField(max_length=512, verbose_name='url دکمه')),
                ('emoji', models.CharField(max_length=10, verbose_name='بهتره که بزاری هاااا')),
            ],
            options={
                'db_table': 'banners',
                'db_table_comment': 'This table is for banners products page.',
                'ordering': ['is_active', 'updated_at'],
            },
        ),
    ]
