# Generated by Django 6.0.6 on 2026-08-10 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_views', to='product.product', verbose_name='کدام محصول'),
        ),
    ]
