# Generated by Django 6.0.6 on 2026-08-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_productview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_view',
        ),
    ]
