# Generated by Django 6.0.6 on 2026-09-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_commentreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
