# Generated by Django 6.0.6 on 2026-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_comment_dislike_remove_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=10),
        ),
    ]
