# Generated by Django 6.0.6 on 2026-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
            ],
            options={
                'db_table': 'news_letter_subscribers',
                'db_table_comment': 'This table is for users who want to subscribe to the newsletter.',
                'ordering': ['is_active', 'email'],
            },
        ),
    ]
