# Generated by Django 6.0.6 on 2026-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام دسته بندی')),
                ('url_name', models.SlugField(max_length=120, unique=True, verbose_name='آدرس دسته بندی در url')),
            ],
            options={
                'db_table': 'blog_categories',
                'db_table_comment': 'This table is used for blog categories.',
                'ordering': ['name'],
            },
        ),
    ]
