# Generated by Django 6.0.6 on 2026-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
            ],
            options={
                'db_table': 'blog_tags',
                'db_table_comment': 'The tags for the blogs are listed in this table.',
                'ordering': ['name'],
            },
        ),
    ]
