# Generated by Django 6.0.6 on 2026-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('name', models.CharField(max_length=450, unique=True, verbose_name='نام مقاله')),
                ('short_text', models.CharField(max_length=600, verbose_name='توضیحات کوتاه')),
                ('summary', models.TextField(verbose_name='خلاصه بلاگ')),
                ('reading_time', models.PositiveSmallIntegerField(verbose_name='مدت زمان مطالعه')),
                ('image', models.ImageField(upload_to='blog/image/', verbose_name='عکس بلاگ')),
                ('category', models.ManyToManyField(related_name='blogs_c', to='blog.blogcategory', verbose_name='دسته بندی ها')),
                ('tag', models.ManyToManyField(related_name='blogs_t', to='blog.blogtag', verbose_name='تگ ها')),
            ],
            options={
                'ordering': ['is_active'],
                'abstract': False,
            },
        ),
    ]
