# Generated by Django 6.0.6 on 2026-09-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTableComment(
            name='blog',
            table_comment='This table is for posts or blogs.',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان این بخش از مقاله')),
                ('content', models.TextField(verbose_name='توضیحات یا متن این قسمت')),
                ('order', models.PositiveSmallIntegerField(help_text='عددی که بالاتر می باشد الویت بیشتری دارد', verbose_name='ترتیب نمایش')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='بلاگ')),
            ],
            options={
                'db_table': 'blog_sections',
                'db_table_comment': 'This table is for the various sections of a blog.',
                'ordering': ['-order'],
            },
        ),
    ]
