# Generated by Django 6.0.6 on 2026-09-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_alter_blog_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=1, max_length=550, verbose_name='آدرس url در بلاگ'),
            preserve_default=False,
        ),
    ]
