# Generated by Django 6.0.6 on 2026-09-23 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('ip', models.GenericIPAddressField(verbose_name='آدرس کاربر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_views', to='blog.blog', verbose_name='کدام بلاک')),
            ],
            options={
                'db_table': 'blog_views',
                'db_table_comment': 'This table is for counting the number of views for a blog.',
                'ordering': ['is_active'],
            },
        ),
    ]
