# Generated by Django 6.0.6 on 2026-09-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_bloglike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglike',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_likes', to='blog.blog', verbose_name='کدام بلاک'),
        ),
    ]
