# Generated by Django 6.0.6 on 2026-09-26 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_bloglike_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sections', to='blog.blog', verbose_name='بلاگ'),
        ),
    ]
