# Generated by Django 6.0.6 on 2026-09-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcomment_blogcommentreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_reactions', to='blog.blogcomment'),
        ),
    ]
