# Generated by Django 6.0.6 on 2026-07-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="نام دسته")),
            ],
            options={
                "db_table": "footer_box",
                "db_table_comment": "f",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="نام لینک")),
                ("url", models.CharField(max_length=512, verbose_name="آدرس url")),
                (
                    "footer_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="site_settings.footerbox",
                    ),
                ),
            ],
            options={
                "db_table": "footer_link",
                "db_table_comment": "d",
                "ordering": ["name"],
            },
        ),
    ]
