# Generated by Django 6.0.6 on 2026-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="url",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="آدرس url"
            ),
        ),
    ]
