# Generated by Django 6.0.6 on 2026-07-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0002_alter_footerlink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="footer_box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="footer_links",
                to="site_settings.footerbox",
            ),
        ),
    ]
