# Generated by Django 6.0.6 on 2026-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_alter_footerlink_footer_box"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام سایت")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_setting/logo",
                        verbose_name="لوگو سایت",
                    ),
                ),
                (
                    "support_email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ایمیل پشتیبانی",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="تلفن تماس"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        max_length=75,
                        null=True,
                        verbose_name="آدرس کانال در تلگرام",
                    ),
                ),
                (
                    "copy_right",
                    models.CharField(max_length=512, verbose_name="متن کپی رایت"),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="ورژن سایت"
                    ),
                ),
                (
                    "site_slogan",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="شعار سایت"
                    ),
                ),
            ],
            options={
                "db_table": "site_settings",
                "db_table_comment": "e",
                "ordering": ["is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال - غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین آپدیت"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=155, verbose_name="نام شبکه اجتماعی"),
                ),
                ("url", models.CharField(max_length=512, verbose_name="آدرس url")),
            ],
            options={
                "db_table": "social_media",
                "db_table_comment": "f",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelTable(
            name="footerbox",
            table="footer_boxes",
        ),
        migrations.AlterModelTable(
            name="footerlink",
            table="footer_links",
        ),
    ]
