# Generated by Django 6.0.6 on 2026-07-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "site_settings",
            "0004_sitesettings_socialmedia_alter_footerbox_table_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMedia",
        ),
    ]
