# Generated by Django 6.0.6 on 2026-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0005_delete_socialmedia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="telegram",
            new_name="telegram_channel",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_channel",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="آدرس اینستاگرام"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_channel",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="آدرس لینکدین"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="telegram_support",
            field=models.CharField(
                blank=True,
                max_length=75,
                null=True,
                verbose_name="آدرس پشتیبانی در تلگرام",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="x_channel",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="آدرس ایکس"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_channel",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="آدرس یوتیوب"
            ),
        ),
    ]
