# Generated by Django 6.0.6 on 2026-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "site_settings",
            "0006_rename_telegram_sitesettings_telegram_channel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_in_footer",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="درباره ما در فوتر"
            ),
        ),
    ]
