# Generated by Django 6.0.6 on 2026-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0007_sitesettings_about_in_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="support_status",
            field=models.BooleanField(
                default=True, verbose_name="فعال - غیر فعال بودن پشتیبانی"
            ),
        ),
    ]
