# Generated by Django 6.0.6 on 2026-08-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_sitesettings_support_status'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='footerbox',
            table_comment="This table is for categorizing the site's footer links",
        ),
        migrations.AlterModelTableComment(
            name='footerlink',
            table_comment="This table is for the site's footer links.",
        ),
        migrations.AlterModelTableComment(
            name='sitesettings',
            table_comment='This table displays site settings, such as the site logo, copyright text, etc.',
        ),
    ]
