# Generated by Django 6.0.6 on 2026-08-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_alter_footerbox_table_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('question', models.TextField(verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('emoji', models.CharField(help_text='حتما پر شود و گرنه ظاهر سایت خراب می شود', max_length=10, verbose_name='ایموجی این سوال')),
            ],
            options={
                'db_table': 'question_answers',
                'db_table_comment': 'This table is for project-wide questions and answers.',
                'ordering': ['is_active'],
            },
        ),
    ]
