# Generated by Django 6.0.6 on 2026-08-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('title', models.CharField(max_length=55, verbose_name='عنوان')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('emoji', models.CharField(blank=True, help_text='این رو اصن بزار نزاری باختی قافله رو', max_length=10, verbose_name='اموجی')),
            ],
            options={
                'db_table': 'features',
                'db_table_comment': 'This class is used for the feature bar.',
                'ordering': ['is_active'],
            },
        ),
    ]
