# Generated by Django 6.0.6 on 2026-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('title', models.CharField(max_length=200, verbose_name='متن نمایش')),
            ],
            options={
                'db_table': 'tickers',
                'db_table_comment': 'This table is used for that purple bar on the main screen.',
                'ordering': ['is_active'],
            },
        ),
    ]
