# Generated by Django 6.0.6 on 2026-08-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_tickers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickers',
            new_name='Ticker',
        ),
    ]
