# Generated by Django 6.0.6 on 2026-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_delete_productquestionanswer'),
        ('site_settings', '0013_rename_tickers_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='position',
            field=models.CharField(choices=[('product_detail', 'صفحه جزییات محصول'), ('home', 'صفحه اصلی')], default=2, help_text='حتما این رو انتخاب کن که داحل کدوم صفحه نمایش داده بشه خیلی ممنون.', verbose_name='کجای صفحه قرار بگیرد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='product',
            field=models.ManyToManyField(help_text='اگر یک محصول یا محصولی نیاز به پرسش و پاسخ خاصی دارد حتما اینجا وارد کن اون محصول رو', related_name='quesions', to='product.product', verbose_name='این پرسش و پاسخ برای کدام محصول'),
        ),
    ]
