# Generated by Django 6.0.6 on 2026-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_questionanswer_position_questionanswer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='position',
            field=models.CharField(blank=True, choices=[('product_detail', 'صفحه جزییات محصول'), ('home', 'صفحه اصلی')], help_text='حتما این رو انتخاب کن که داحل کدوم صفحه نمایش داده بشه خیلی ممنون.', null=True, verbose_name='کجای صفحه قرار بگیرد'),
        ),
    ]
