# Generated by Django 6.0.6 on 2026-08-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_alter_questionanswer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='emoji',
            field=models.CharField(blank=True, help_text='حتما پر شود و گرنه ظاهر سایت خراب می شود', max_length=10, null=True, verbose_name='ایموجی این سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='position',
            field=models.CharField(choices=[('product_detail', 'صفحه جزییات محصول'), ('home', 'صفحه اصلی')], help_text='حتما این رو انتخاب کن که داحل کدوم صفحه نمایش داده بشه خیلی ممنون.', verbose_name='کجای صفحه قرار بگیرد'),
        ),
    ]
