# Generated by Django 6.0.6 on 2026-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_delete_productquestionanswer'),
        ('site_settings', '0016_alter_questionanswer_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='emoji',
            field=models.CharField(help_text='حتما پر شود و گرنه ظاهر سایت خراب می شود', max_length=10, verbose_name='ایموجی این سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='product',
            field=models.ManyToManyField(blank=True, help_text='اگر یک محصول یا محصولی نیاز به پرسش و پاسخ خاصی دارد حتما اینجا وارد کن اون محصول رو', null=True, related_name='quesions', to='product.product', verbose_name='این پرسش و پاسخ برای کدام محصول'),
        ),
    ]
