# Generated by Django 6.0.6 on 2026-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_delivery_info_alter_product_tag'),
        ('site_settings', '0017_alter_questionanswer_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='emoji',
            field=models.CharField(blank=True, help_text='حتما پر شود و گرنه ظاهر سایت خراب می شود اگر پوزیشن محصول برای جزییات محصول هست نیازی نیست این قسمت پر شود', max_length=10, null=True, verbose_name='ایموجی این سوال'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='product',
            field=models.ManyToManyField(help_text='اگر یک محصول یا محصولی نیاز به پرسش و پاسخ خاصی دارد حتما اینجا وارد کن اون محصول رو', related_name='quesions', to='product.product', verbose_name='این پرسش و پاسخ برای کدام محصول'),
        ),
    ]
