# Generated by Django 6.0.6 on 2026-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_delivery_info_alter_product_tag'),
        ('site_settings', '0018_alter_questionanswer_emoji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('short_title', models.CharField(max_length=35, verbose_name='عنوان کوتاه')),
                ('main_title', models.CharField(max_length=120, verbose_name='عنوان اصلی')),
                ('desctiption', models.CharField(max_length=350, verbose_name='توضیحات')),
                ('btn_text', models.CharField(max_length=55, verbose_name='متن درون دکمه')),
                ('btn_url', models.CharField(max_length=512, verbose_name='url دکمه')),
                ('small_image', models.ImageField(upload_to='site_setting/hero_section', verbose_name='عکس کوچک')),
                ('big_image', models.ImageField(upload_to='site_setting/hero_section', verbose_name='عکس بزرگ')),
            ],
            options={
                'db_table': 'hero_section',
                'db_table_comment': 'This table is for the upper section of the site, below the header.',
                'ordering': ['is_active', 'updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='product',
            field=models.ManyToManyField(blank=True, help_text='اگر یک محصول یا محصولی نیاز به پرسش و پاسخ خاصی دارد حتما اینجا وارد کن اون محصول رو', related_name='quesions', to='product.product', verbose_name='این پرسش و پاسخ برای کدام محصول'),
        ),
    ]
