# Generated by Django 6.0.6 on 2026-08-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0019_herosection_alter_questionanswer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='desctiption',
            new_name='description',
        ),
    ]
