# Generated by Django 6.0.6 on 2026-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0020_rename_desctiption_herosection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='position',
            field=models.CharField(choices=[('product_detail', 'صفحه جزییات محصول'), ('home', 'صفحه اصلی')], help_text='حتما این رو انتخاب کن که داحل کدوم صفحه نمایش داده بشه خیلی ممنون.', null=True, verbose_name='کجای صفحه قرار بگیرد'),
        ),
    ]
