# Generated by Django 6.0.6 on 2026-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0021_feature_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='position',
            field=models.CharField(choices=[('product_detail', 'صفحه جزییات محصول'), ('home', 'صفحه اصلی')], help_text='حتما این رو انتخاب کن که داحل کدوم صفحه نمایش داده بشه خیلی ممنون.', verbose_name='کجای صفحه قرار بگیرد'),
        ),
    ]
