# Generated by Django 6.0.6 on 2026-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0023_alter_feature_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال - غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('main_title', models.CharField(max_length=75, verbose_name='عنوان کوتاه')),
                ('short_title', models.CharField(max_length=75, verbose_name='عنوان اصلی')),
                ('btn_text', models.CharField(blank=True, help_text='اگر میخای این بنر اصلی و بزرگ باشه این قسمت رو پر کن', max_length=55, null=True, verbose_name='متن درون دکمه')),
                ('btn_url', models.CharField(blank=True, help_text='اگر میخای این بنر اصلی و بزرگ باشه این قسمت رو پر کن', max_length=512, null=True, verbose_name='url دکمه')),
                ('image', models.ImageField(upload_to='site_setting/SpecialOffer', verbose_name='تصویر بنر')),
            ],
            options={
                'db_table': 'special_offers',
                'db_table_comment': 'This class is for special_offers index page.',
                'ordering': ['is_active', 'updated_at'],
            },
        ),
    ]
