# Generated by Django 6.0.6 on 2026-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0024_specialoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='main_title',
            field=models.CharField(max_length=75, verbose_name='عنوان اصلی'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='short_title',
            field=models.CharField(max_length=75, verbose_name='عنوان کوتاه'),
        ),
    ]
