# Generated by Django 6.0.6 on 2026-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0025_alter_specialoffer_main_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='btn_url',
            field=models.CharField(blank=True, help_text='این قسمت رو برای هر بنری پر کن حتما', max_length=512, null=True, verbose_name='url دکمه'),
        ),
    ]
