# Generated by Django 6.0.6 on 2026-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0026_alter_specialoffer_btn_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='position',
            field=models.CharField(choices=[('product_detail', 'صفحه جزییات محصول'), ('home', 'صفحه اصلی'), ('contact', 'صفحه تماس با ما')], help_text='حتما این رو انتخاب کن که داحل کدوم صفحه نمایش داده بشه خیلی ممنون.', verbose_name='کجای صفحه قرار بگیرد'),
        ),
    ]
